GDSC SKHU Web - 이예슬
GDSC-SKHU/GDSC-Web-Assignment-05 pull request #1
Opened 2022-12-09 01:46 UTC by yeaseul7

## Description

- 어쩌구 저쩌구
- 

## Important content

- 어쩌구 저쩌구
- 

## Question

- 어쩌구 저쩌구
- 

## Reference

2022-12-12 09:46 UTC, hyesungoh commented
예슬님 PR 내용 작성해 주세요 ~

2022-12-13 16:17 UTC, hyesungoh requested changes
아직 작업중이신건가요?? 앞으로는 과제가 끝나면 PR을 작성해 주세요 ~~
---
리퀘체 이유 

- `GlobalStyle` 재관님이나 효중님 PR 확인하셔서 수정해 주세요 ~~
- purchase route가 없습니다 ~ 과제 가이드라인 확인해 주세요

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/index.tsx
> +}
이렇게 작성하신 이유가 무엇인가요? `Movie`의 내용을 여기에 적어도 되는 거 아닌가요 ??

> 관련해 자세한 내용은 재관님 PR을 봐주세요

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +    imageUrl: "/데시벨.jpeg",
밖에 선언하신거 👍 👍

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +const SubIntro = ({ setSubBox, v }: any) => {
인터페이스 선언하시면 되는데 `any`를 사용하신 이유가 무엇인가요?

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +              <GlobalStyle />
이러면 글로벌 스타일이 여러개 렌더링되겠죠??

글로벌 스타일은 전역 스타일이기 때문에 이렇게 여러개 렌더링 되는 건 존재 이유랑 부합하지 않은 거 같아요

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +  const [isEmpty, setIsEmpty] = useState<boolean>(true);
이 상태는 사용되고 있지 않는데, 존재한느 이유가 무엇인가요?

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +          {!subBox ? <SubIntro {...{ setSubBox, v }} /> : null}
```suggestion
          {!subBox && <SubIntro {...{ setSubBox, v }} />}
```

의미가 퇴색되는 삼항 연산자는 지양해 주세요~

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/components/Movie.tsx
> +const OnMovieBlock = ({ v }: any) => {
마찬가지로 `any`는 꼭 필요한 경우가 아니면 사용을 지양해 주세요

any를 쓰면 타입스크립트를 쓰는 이유가 없어지는 것과 마찬가지입니다

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +    id: 1,
지금 똑같은 상수가 계속해서 선언되고 있어요

이런 경우 변경이 있을 때 선언되는 곳마다 바꿔야겠죠??

굉장히 안티 패턴이라고 생각되고 그렇게 느끼실 텐데. 이런 경우 따로 모듈화해서 빼두시면 돼요

`src/constants/movies.ts`

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +  };
강의에도 언급했었지만, 이렇게 되면 이전값에 대한 보장을 받지 못하죠?

set stating은 비동기적으로 동작하기 때문에 ??

prev 값을 활용해 바꿔주세요~

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +  };
지금 성인과 어린이를 가르는 함수인데, 함수 명에 단지 1을 붙이는 방법은 굉장히 부적절한 방법인 거 같아요

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +      ) : null}
여기도 마찬가지로 `&&` 연산자로 대체할 수 있겠죠?

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +              ))}
여기서 `v`라는 이름은 의미가 있나요? 이렇게 의미 없는 변수가 하나 둘 쌓이다보면 걷잡을 수 없이 레거시가 돼요

한 줄 한 줄 매 글자 모두 의미를 담을려고 노력하시면 좋을 거 같아요

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/booking.tsx
> +  //???: 공통 로직은 추출해라
코멘트 남겨주신 것처럼 굉장히 반복되는 부분이 많죠 ?? 

해당 부분을 어떻게 수정할 수 있을까요?

2022-12-13 16:17 UTC, hyesungoh commented on yeaseul/src/pages/_document.tsx
> +}
Next.js 공식 문서도 함수 컴포넌트로 변경됐는데, 여기서 클래스 컴포넌트로 Document를 작성하신 이유가 무엇인가요 ㅋㅋㅋ

https://nextjs.org/docs/advanced-features/custom-document

2022-12-13 23:56 UTC, zoeyourlife commented on yeaseul/src/components/ChairBox.tsx
> +    </Seatbtn>
오 . . . 많이 배워갑니다 ! 👍

2022-12-13 23:56 UTC, zoeyourlife commented on yeaseul/src/components/ChairBox.tsx
> +  };
디테일까지 ~!! 💯

2022-12-13 23:56 UTC, zoeyourlife commented on yeaseul/src/components/ChairBox.tsx
> +              </div>
👍 👍

2022-12-13 23:56 UTC, zoeyourlife commented on yeaseul/src/components/ReservationModal.tsx
> +                  alert("예약 완료되었습니다.");
👍 💯

2022-12-13 23:56 UTC, zoeyourlife commented on yeaseul/src/pages/_document.tsx
> +}
뭔가 되게 어려워 보이는 개념이네요 . .

2022-12-14 03:54 UTC, yeaseul7 commented on yeaseul/src/pages/index.tsx
> +}
아...처음엔 미리 Movie를 만들어서 생각을 못했었는데 다시 보니까 그렇네욤..

2022-12-14 03:55 UTC, yeaseul7 commented on yeaseul/src/components/Movie.tsx
> +              <GlobalStyle />
넵 수정했습니당 :>

2022-12-14 03:55 UTC, yeaseul7 commented on yeaseul/src/components/Movie.tsx
> +  const [isEmpty, setIsEmpty] = useState<boolean>(true);
안쓰는걸 다 제거 했어야 했는데 제거하지 못했습니다... 🫢

2022-12-14 03:56 UTC, yeaseul7 commented on yeaseul/src/components/Movie.tsx
> +          {!subBox ? <SubIntro {...{ setSubBox, v }} /> : null}
넹! 수정했습니다!

2022-12-14 03:56 UTC, yeaseul7 commented on yeaseul/src/components/Movie.tsx
> +const OnMovieBlock = ({ v }: any) => {
아...넵 명심하겠습니다:)

2022-12-14 03:57 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +    id: 1,
아 따로 빼둔것도 있는데 저건 반복해서 썼네요... 수정했습니다!
모듈화..

2022-12-14 04:00 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +  };
네!

2022-12-14 04:00 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +  };
이름에 의미가 없네욤.. 수정했습니다!

2022-12-14 04:00 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +          //js 문법 생각 js에서는 key:value 근데 같으니까 생략
옹...넵!

2022-12-14 04:00 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +      ) : null}
네! 모두 수정했습니당

2022-12-14 04:01 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +      <GlobalStyle />
🥲

2022-12-14 04:02 UTC, yeaseul7 commented on yeaseul/src/pages/booking.tsx
> +              ))}
넵!

2022-12-14 04:03 UTC, yeaseul7 commented on yeaseul/src/pages/_document.tsx
> +}
이건 자꾸 에러나길래 구글해서 퍼온 코드입니다..저 코드 내용을 이해하지 못했어욤..일단 에러가 없어져서 쓰긴 했는데..🥲

2022-12-14 04:03 UTC, yeaseul7 commented on yeaseul/src/pages/_document.tsx
> +}
저도.. 잘 모르는 개념..입니다...ㅠ....ㅠㅠㅠㅠ

2022-12-14 09:26 UTC, hyesungoh approved these changes

2022-12-14 11:38 UTC, merged