GDSC SKHU Web - 이은지
GDSC-SKHU/GDSC-Web-Assignment-05 pull request #2
Opened 2022-12-12 15:01 UTC by Lee2Eunji

## Description

- 영화 예매 사이트 구현
- 리스트 렌더링(index), 좌석 선택(booking), 결제창(purchase)

## Important content

- booking에서 좌석을 선택하지 않았을 때 alert 뜨도록 구현
- Global Style 폰트 적용

## Question

- PR 날리고 계속 구현하겠지만, useState로 사진 넘기는 방법이 궁금합니다..

## Reference

- https://velog.io/@sbinha/next.js-Router%EB%A5%BC-%ED%86%B5%ED%95%B4-props-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84 (router query 참고)

2022-12-13 14:04 UTC, hyesungoh requested changes
👍 👍 고생의 흔적이 잘 보이는 과제물이네요 👍 💯 

추가적으로 `prettier`를 이용해 코드 포매팅을 맞춰주시는 것을 습관화 하시면 좋을 거 같아요

--- 

리퀘스트 체인지 이유

https://styled-components.com/docs/api#createglobalstyle

2022-12-13 14:04 UTC, hyesungoh commented on eunji/src/components/Select.tsx
> +            setPrice(600);
`onReset`에 `setPrice` 로직도 있으면 어떨까요?

2022-12-13 14:04 UTC, hyesungoh commented on eunji/src/components/Select.tsx
> +        });
위에서 return을 하고 있기 때문에 여기서 else가 하는 일은 사실 없을 거 같아요
```suggestion
            return;
        }
        // 그렇지 않으면(선택을 하면)
       router.push({
            // purchase로 이동하고
            pathname: '/purchase',
            // 해당 값들을 purchase로 넘겨라
            query: { poster: poster, name: name, person: person, price: total },
        });
```

이렇게 작성하는게 `early return`이라는 클린 코드 기법 중 하난데, 취향을 타긴 하지만 저는 좋아합니다

2022-12-13 14:04 UTC, hyesungoh commented on eunji/src/pages/purchase.tsx
> +    }
🤣

2022-12-13 14:04 UTC, hyesungoh commented on eunji/src/pages/purchase.tsx
> +}
만약 실 서비스라고 했을 때, `rotuer.query.` 안에 값들이 없을 때는 어떻게 대응할 수 있을까요?

2022-12-13 15:54 UTC, lgyn10 commented on eunji/src/components/Select.tsx
> +    }
저도 이렇게 코드 짤 수 있도록 더 공부해야겠네요..😢

2022-12-14 00:49 UTC, Lee2Eunji commented on eunji/src/components/Movies.tsx
> +                <Link href="/booking"><StyledImg src={imgSrc} /></Link>
alt를 그냥 쓰니까 내용도 화면에 같이 표시되더라고요ㅠ
수정했습니다!

2022-12-14 00:53 UTC, Lee2Eunji commented on eunji/src/components/Movies.tsx
> +            <Link href="/booking" style={{textDecoration: 'none', color: 'black'}}><StyledH2>{title}</StyledH2></Link>
괄호로 처리하는군요! 적용했습니다

2022-12-14 00:54 UTC, Lee2Eunji commented on eunji/src/components/Select.tsx
> +        }
저도 값이 유니크하지 않을 때는 어떡하지.. 하면서 코드를 짰는데 id 값을 불러오는 방법이 있었군요ㅠㅠㅠ 추후에 수정하겠습니다!

2022-12-14 00:55 UTC, Lee2Eunji commented on eunji/src/components/Select.tsx
> +    }, [price, person]);
의미 없는 코드였던 것 같아요 바로 삭제했습니다!

2022-12-14 00:56 UTC, Lee2Eunji commented on eunji/src/components/Select.tsx
> +
네 유의하겠습니다..!

2022-12-14 00:57 UTC, Lee2Eunji commented on eunji/src/components/Select.tsx
> +            setPrice(600);
setPrice 로직이라는 게 setPrice도 reset 내에 설정하라는 말씀이신 건가요?!

2022-12-14 00:59 UTC, Lee2Eunji commented on eunji/src/components/Select.tsx
> +        });
else를 빼면 안 되는 줄 알았어요ㅠ 덕분에 새로운 기법 알아갑니다!

2022-12-14 01:00 UTC, Lee2Eunji commented on eunji/src/pages/purchase.tsx
> +}
그냥 딱 보고 생각했을 때는 빈값, 즉 0으로 처리하면 되지 않을까 싶은데 더 고민해보고 찾아보겠습니다!

2022-12-14 09:28 UTC, hyesungoh approved these changes

2022-12-14 11:38 UTC, merged