GDSC SKHU Web - 이찬균
GDSC-SKHU/GDSC-Web-Assignment-05 pull request #5
Opened 2022-12-13 15:47 UTC by lgyn10

## Description
- 영화 선택 예매 페이지
- 영화 선택 및 좌석 선택 시 인원 및 가격 조회
- 예매정보 화면 구현 

## Important content

## Question

- 6번째 seat이 선택하면 빨간색으로 변경된 후, 다시 눌러도 되돌아오지 않아요.. 나머지 seat과 코드 동일하게 했는데 왜 이런거죠..?
- 자바스크립트가 아직 어렵습니다.. 이제 종강도 했으니 더 공부하도록 하겠습니다..! 
## Reference

2022-12-13 16:02 UTC, hyesungoh requested changes
고생하셨어요 👍 👍 👍  누구보다 노력의 흔적이 보입니다 ㅋㅋㅋㅋ

리퀘체는 글로벌 스타일 적용 방법만 다른 분들 PR 확인해 수정해 주시면 될 거 같아요

2022-12-13 16:02 UTC, hyesungoh commented on changyunlee/src/pages/Booking.tsx
> +  };
지금 이렇게 반복되는 로직으로 구현할 수 있는게 1 단계라고 친다면

여기에서 절대 절대 만족하면 안돼요 

잘 아시겠지만, 지금 같은 경우에 변경에 대응하기도 힘들고 확장하기도 힘들겠죠??

지금 쓴 로직들중에 분명히 반복되는 곳이 있고 이를 해결하실 수 있어야 해요

2022-12-14 00:39 UTC, Lee2Eunji commented on changyunlee/src/pages/Booking.tsx
> +    }
저도 이러한 방식으로 했는데, 가격이 유니크 할 때만 적용돼서 다른 방법 구상 중입니다.

2022-12-15 02:49 UTC, lgyn10 commented on changyunlee/src/components/Movie.tsx
> +        </StyledInfo>
넵!

2022-12-15 02:50 UTC, lgyn10 commented on changyunlee/src/pages/Booking.tsx
> +  const [color12, setColor12] = useState<boolean>(true);
ㅜㅜ

2023-07-14 04:28 UTC, closed without merging